import type { MemberOption, TaskRecord, WorkspaceData } from "./types";

export const demoWorkspace: WorkspaceData = {
  workspace: {
    id: "demo-workspace",
    name: "Main Engineering Hub",
    role: "admin",
  },
  user: {
    id: "demo-user",
    email: "somchai@orangecat.work",
    displayName: "Somchai Dech",
  },
  projects: [
    {
      id: "demo-website-redesign",
      name: "Website Redesign Q4",
      description: "ปรับประสบการณ์เว็บไซต์และระบบ Design System",
      color: "#0B63F6",
      updated_at: "2026-09-27T03:00:00.000Z",
    },
    {
      id: "demo-mobile-app",
      name: "Mobile App V1",
      description: "วางโครงสร้างแอปและ Core API สำหรับเวอร์ชันแรก",
      color: "#FF9418",
      updated_at: "2026-09-26T08:30:00.000Z",
    },
    {
      id: "demo-brand-refresh",
      name: "Brand Refresh",
      description: "ปรับอัตลักษณ์และคู่มือการใช้งานแบรนด์",
      color: "#0F7490",
      updated_at: "2026-09-25T10:15:00.000Z",
    },
  ],
};

export const demoMembers: MemberOption[] = [
  { id: "demo-user", displayName: "Somchai Dech", email: "somchai@orangecat.work", role: "admin", joinedAt: "2026-01-12T00:00:00Z" },
  { id: "member-1", displayName: "Nattapol Sukhum", email: "nattapol@orangecat.work", role: "member", joinedAt: "2026-02-01T00:00:00Z" },
  { id: "member-2", displayName: "Phattra Danupat", email: "phattra@orangecat.work", role: "member", joinedAt: "2026-02-15T00:00:00Z" },
  { id: "guest-1", displayName: "Siriporn T.", email: "siriporn@client.co.th", role: "guest", joinedAt: "2026-03-10T00:00:00Z" },
];

const now = "2026-09-27T03:00:00.000Z";

export const demoTasks: TaskRecord[] = [
  {
    id: "task-auth",
    projectId: "demo-website-redesign",
    parentTaskId: null,
    title: "พัฒนาระบบ Authentication และสิทธิ์ RLS",
    description: "ตั้งค่า Supabase Auth, cookie session และนโยบาย Row Level Security สำหรับทุกบทบาท",
    status: "in_progress",
    priority: "high",
    assigneeId: "demo-user",
    startDate: "2026-09-18",
    dueDate: "2026-09-28",
    position: 1000,
    createdAt: "2026-09-10T02:00:00.000Z",
    updatedAt: now,
  },
  {
    id: "sub-auth-schema",
    projectId: "demo-website-redesign",
    parentTaskId: "task-auth",
    title: "ตั้งค่า Supabase Auth schema",
    description: null,
    status: "done",
    priority: null,
    assigneeId: "demo-user",
    startDate: "2026-09-18",
    dueDate: "2026-09-20",
    position: 1000,
    createdAt: "2026-09-10T03:00:00.000Z",
    updatedAt: now,
  },
  {
    id: "sub-auth-rls",
    projectId: "demo-website-redesign",
    parentTaskId: "task-auth",
    title: "เขียน Row Level Security สำหรับ 3 Roles",
    description: null,
    status: "done",
    priority: null,
    assigneeId: "demo-user",
    startDate: "2026-09-20",
    dueDate: "2026-09-24",
    position: 2000,
    createdAt: "2026-09-10T04:00:00.000Z",
    updatedAt: now,
  },
  {
    id: "sub-auth-test",
    projectId: "demo-website-redesign",
    parentTaskId: "task-auth",
    title: "ทดสอบ Guest และ Cross-workspace access",
    description: null,
    status: "in_progress",
    priority: null,
    assigneeId: "member-1",
    startDate: "2026-09-25",
    dueDate: "2026-09-28",
    position: 3000,
    createdAt: "2026-09-10T05:00:00.000Z",
    updatedAt: now,
  },
  {
    id: "task-list",
    projectId: "demo-website-redesign",
    parentTaskId: null,
    title: "พัฒนา List View และ Inline Edit",
    description: "แสดง Task/Subtask แบบลำดับชั้น พร้อมแก้ไขสถานะ ผู้รับผิดชอบ และวันที่ได้รวดเร็ว",
    status: "in_progress",
    priority: "high",
    assigneeId: "member-2",
    startDate: "2026-09-22",
    dueDate: "2026-10-02",
    position: 2000,
    createdAt: "2026-09-12T03:00:00.000Z",
    updatedAt: "2026-09-26T08:00:00.000Z",
  },
  {
    id: "task-docs",
    projectId: "demo-website-redesign",
    parentTaskId: null,
    title: "เตรียมเอกสาร API และคู่มือทีม",
    description: "สรุปการตั้งค่า environment และ flow การทำงานสำหรับทีมพัฒนา",
    status: "todo",
    priority: "medium",
    assigneeId: "member-1",
    startDate: "2026-09-28",
    dueDate: "2026-10-05",
    position: 3000,
    createdAt: "2026-09-14T03:00:00.000Z",
    updatedAt: "2026-09-25T08:00:00.000Z",
  },
  {
    id: "task-qa",
    projectId: "demo-website-redesign",
    parentTaskId: null,
    title: "ทดสอบ End-to-end และ Cross-view consistency",
    description: "ทดสอบ flow หลักและยืนยันว่าทุก View ใช้ Task record ชุดเดียวกัน",
    status: "todo",
    priority: "high",
    assigneeId: null,
    startDate: "2026-10-02",
    dueDate: "2026-10-10",
    position: 4000,
    createdAt: "2026-09-15T03:00:00.000Z",
    updatedAt: "2026-09-25T09:00:00.000Z",
  },
];
